import io

def generate_html_report(overall_kpis, channel_metrics_df, fig_waterfall, fig_trend, fig_bar, fig_scat):
    """
    Generates a standalone HTML report with embedded Plotly charts.
    """
    
    # Convert figs to HTML div strings
    # include_plotlyjs='cdn' ensures the file is smaller and uses CDN for library
    waterfall_html = fig_waterfall.to_html(full_html=False, include_plotlyjs='cdn')
    trend_html = fig_trend.to_html(full_html=False, include_plotlyjs=False)
    bar_html = fig_bar.to_html(full_html=False, include_plotlyjs=False)
    scat_html = fig_scat.to_html(full_html=False, include_plotlyjs=False)
    
    # Basic CSS
    css = """
    <style>
        body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .metric-container { display: flex; justify-content: space-around; background: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 40px; }
        .metric-box { text-align: center; }
        .metric-value { font-size: 24px; font-weight: bold; color: #0F172A; }
        .metric-label { font-size: 14px; color: #64748b; }
        .chart-section { margin-bottom: 50px; }
        .footer { margin-top: 50px; border-top: 1px solid #eee; padding-top: 20px; font-size: 12px; color: #999; text-align: center; }
    </style>
    """
    
    html_content = f"""
    <html>
    <head>
        <title>Mahanka Unit Economics Report</title>
        {css}
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    </head>
    <body>
        <div class="header">
            <h1>Mahanka Unit Economics Report</h1>
            <p>Generated for D2C Brand Analysis</p>
        </div>
        
        <div class="metric-container">
            <div class="metric-box">
                <div class="metric-value">₹{overall_kpis['Gross_Revenue']:,.0f}</div>
                <div class="metric-label">Gross Revenue</div>
            </div>
            <div class="metric-box">
                <div class="metric-value">₹{overall_kpis['Net_Revenue']:,.0f}</div>
                <div class="metric-label">Net Revenue</div>
            </div>
            <div class="metric-box">
                <div class="metric-value">{overall_kpis['Return_Rate']:.1%}</div>
                <div class="metric-label">Return Rate</div>
            </div>
            <div class="metric-box">
                <div class="metric-value">{overall_kpis['Blended_CM_Pct']:.1%}</div>
                <div class="metric-label">Contribution Margin</div>
            </div>
            <div class="metric-box">
                <div class="metric-value">₹{overall_kpis['Blended_CAC']:.0f}</div>
                <div class="metric-label">Blended CAC</div>
            </div>
            <div class="metric-box">
                <div class="metric-value">{overall_kpis['Blended_ROAS']:.2f}x</div>
                <div class="metric-label">Blended ROAS</div>
            </div>
        </div>
        
        <div class="chart-section">
            <h2>Profitability Waterfall</h2>
            {waterfall_html}
        </div>
        
        <div class="chart-section">
            <div style="display:flex; gap: 20px;">
                <div style="width: 50%;">
                    <h3>Contribution Margin by Channel</h3>
                    {bar_html}
                </div>
                <div style="width: 50%;">
                    <h3>ROAS vs Volume</h3>
                    {scat_html}
                </div>
            </div>
        </div>

        <div class="chart-section">
            <h2>Monthly Trends</h2>
            {trend_html}
        </div>
        
        <div class="footer">
            Generated by Mahanka Unit Economics Calculator. <br>
            Book a consultation to improve these numbers: <b>mahanka.com/audit</b>
        </div>
    </body>
    </html>
    """
    
    return html_content
